#!/usr/bin/env python
#Problem 1
#Opens CSV file and sets value

wfile = open("/ufrc/bsc4452/share/Class_Files/data/CO-OPS__8729108__wl.csv","r")
maxt = 0.0
datet = 0.0

#Sets loop to find max value and correlating time and date
for line in wfile:
    try:
        w= (line.split)(",")[0]
        p = float(line.split(",")[1])
        if maxt < p:
            maxt = p
            datet = w
    except ValueError:
         pass

       
#Prints Date then water value
print ("Time and date of maximum water value:",datet,maxt)
