#!/usr/bin/env python
#Problem 2
#Utilize pandas and read csv file
#import pandas as dataframe through pandas
df = pd.read_csv('/ufrc/bsc4452/share/Class_Files/data/CO-OPS__8729108__wl.csv')
#Extracts maximum value of dataframe
read = df[df[' Water Level'] == df[' Water Level'].max()]
#Print values
print(f"Water Level: {read[' Water Level'].values[0]}")
print(f"Date and Time: {read['Date Time'].values[0]}")
